# Dependencies
markdown: kramdown
highlighter: rouge
remote_theme: fongandrew/hydeout

# Setup
title: '포스트 왜 안뜨냐곸ㅋㅋㅋㅋ'
tagline: 'Study Logs'
description: 'Study Logs'
url: https://TaeAhnK.github.io
baseurl: ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

timezone: Asia/Seoul
author:
  name: 'TaeAhnK'

paginate: 5
paginate_path: '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link: true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
                                
g-analytics: UA-173507158-1