title: TaeAhnK's Portfolio
description: 게임 클라이언트 개발자 김태안의 포트폴리오입니다.
lang: ko-KR
url: "https://taeahnk.github.io"
baseurl: ""

excerpt_separator: "<!-- preview -->"

collections:
  projects:
    output: true
    permalink: /projects/:name/

index:
  projects_count: 4
  other_projects_count: 4
  current_projects_count: 1
  
  projects_columns: 2
  other_projects_columns: 4
  current_projects_columns: 1

print:
  projects_count: 4
  other_projects_count: 0
  current_projects_count: 0
